language: android
jdk: oraclejdk8

addons:
  apt:
    packages:
      - lynx

env:
 global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.3
android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
script:
    - ./gradlew build check
after_script:
- if [ -f /home/travis/build/adrcotfas/Goodtime/app/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/adrcotfas/Goodtime/app/build/outputs/lint-results-debug.html; fi
